"""Initial consolidated migration

Revision ID: 000d37c1f9f0
Revises: 
Create Date: 2024-09-04 21:49:12.224272

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '000d37c1f9f0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.drop_constraint('fk_party_id', type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_party_id', 'parties', ['party_id'], ['id'])

    # ### end Alembic commands ###
