"""Add party version column for optimistic locking

Revision ID: 00d5f6f873e2
Revises: ab09d77d6ce6
Create Date: 2024-06-22 10:42:32.851483

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00d5f6f873e2'
down_revision = 'ab09d77d6ce6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parties', schema=None) as batch_op:
        batch_op.add_column(sa.Column('version', sa.Integer(),
                            nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parties', schema=None) as batch_op:
        batch_op.drop_column('version')

    # ### end Alembic commands ###
