"""Add panicked column to Character

Revision ID: 066ddbbebeb8
Revises: 15cdd43b0112
Create Date: 2025-07-24 13:31:28.442866

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '066ddbbebeb8'
down_revision = '15cdd43b0112'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('panicked', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.drop_column('panicked')

    # ### end Alembic commands ###
