"""add container and animal columns

Revision ID: 0ad261bc194f
Revises: 9f2fc5c70feb
Create Date: 2023-09-16 14:58:48.439659

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ad261bc194f'
down_revision = '9f2fc5c70feb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('container', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('animal', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.drop_column('animal')
        batch_op.drop_column('container')

    # ### end Alembic commands ###
