"""add custom_background and custom_name

Revision ID: 1ad76dc75bb3
Revises: 0ad261bc194f
Create Date: 2023-10-29 13:23:41.997056

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ad76dc75bb3'
down_revision = '0ad261bc194f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('custom_name', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('custom_background', sa.String(length=64), nullable=True))
        batch_op.alter_column('background',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=64),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.alter_column('background',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.drop_column('custom_background')
        batch_op.drop_column('custom_name')

    # ### end Alembic commands ###
