"""add custom_image and image_url fields

Revision ID: 2f7b0a53b49e
Revises: dd45c913e735
Create Date: 2024-01-03 22:20:21.531103

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f7b0a53b49e'
down_revision = 'dd45c913e735'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('custom_image', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('image_url', sa.String(length=512), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.drop_column('image_url')
        batch_op.drop_column('custom_image')

    # ### end Alembic commands ###
