"""add overburdened

Revision ID: 3bd7bfa1b372
Revises: beb9c8d6f2dd
Create Date: 2024-05-04 14:58:05.991832

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3bd7bfa1b372'
down_revision = 'beb9c8d6f2dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('overburdened', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.drop_column('overburdened')

    # ### end Alembic commands ###
