"""adjust armor to string field

Revision ID: 443ca2ccd85b
Revises: 36cff1a1f4ba
Create Date: 2024-01-20 16:44:37.845913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '443ca2ccd85b'
down_revision = '36cff1a1f4ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.alter_column('armor',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=16),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.alter_column('armor',
               existing_type=sa.String(length=16),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
