"""add owner_username field to parties

Revision ID: 6cc8c4b2b44b
Revises: 4306e31dbfaf
Create Date: 2024-02-24 19:44:09.963943

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6cc8c4b2b44b'
down_revision = '4306e31dbfaf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parties', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner_username', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parties', schema=None) as batch_op:
        batch_op.drop_column('owner_username')

    # ### end Alembic commands ###
