"""add items column

Revision ID: 9f2fc5c70feb
Revises: eb19ae9b851e
Create Date: 2023-08-31 20:31:37.686919

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f2fc5c70feb'
down_revision = 'eb19ae9b851e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('items', sa.String(length=1000)))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.drop_column('items')

    # ### end Alembic commands ###
