"""Reset migrations

Revision ID: abbbce54689f
Revises: 
Create Date: 2024-09-13 11:28:33.987727

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abbbce54689f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.drop_constraint('fk_party_id', type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_party_id', 'parties', ['party_id'], ['id'])

    # ### end Alembic commands ###
