"""add items and containers to party model

Revision ID: beb9c8d6f2dd
Revises: 6cc8c4b2b44b
Create Date: 2024-03-08 20:46:37.585635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'beb9c8d6f2dd'
down_revision = '6cc8c4b2b44b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parties', schema=None) as batch_op:
        batch_op.add_column(sa.Column('items', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('containers', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parties', schema=None) as batch_op:
        batch_op.drop_column('containers')
        batch_op.drop_column('items')

    # ### end Alembic commands ###
