"""add traits column

Revision ID: c14144e7baef
Revises: 3bd7bfa1b372
Create Date: 2024-05-30 08:53:20.160385

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c14144e7baef'
down_revision = '3bd7bfa1b372'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('traits', sa.String(length=2000), nullable=True))
        batch_op.drop_column('overburdened')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('overburdened', sa.BOOLEAN(), nullable=True))
        batch_op.drop_column('traits')

    # ### end Alembic commands ###
