"""remove container and animal columns, add containers column

Revision ID: cd5bb0fc8a17
Revises: 1ad76dc75bb3
Create Date: 2023-11-04 20:25:37.472536

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd5bb0fc8a17'
down_revision = '1ad76dc75bb3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('containers', sa.String(), nullable=True))
        batch_op.drop_column('animal')
        batch_op.drop_column('container')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('container', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('animal', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('containers')

    # ### end Alembic commands ###
