"""add characters table

Revision ID: eb19ae9b851e
Revises: a086d904d7cd
Create Date: 2023-08-26 21:38:44.181297

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb19ae9b851e'
down_revision = 'a086d904d7cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('characters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url_name', sa.String(length=100), nullable=True),
    sa.Column('owner', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('background', sa.String(length=100), nullable=False),
    sa.Column('strength', sa.Integer(), nullable=True),
    sa.Column('strength_max', sa.Integer(), nullable=True),
    sa.Column('dexterity', sa.Integer(), nullable=True),
    sa.Column('dexterity_max', sa.Integer(), nullable=True),
    sa.Column('willpower', sa.Integer(), nullable=True),
    sa.Column('willpower_max', sa.Integer(), nullable=True),
    sa.Column('hp', sa.Integer(), nullable=True),
    sa.Column('hp_max', sa.Integer(), nullable=True),
    sa.Column('deprived', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['owner'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('characters')
    # ### end Alembic commands ###
